title: Alex Xie
email: alex.xie7734@gmail.com
shortbio: >-
  MLT student at CMU LTI working on code generation.
author_display: true
author: Alex Xie
github_username: axie66
linkedin_username: axie
# curriculum:
#   url: /assets/resume.pdf
nb_posts_page: 10
markdown: kramdown